// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYeipFKApz2fIZ13yDYy7MmMXyr7N7Tfw',
    appId: '1:693469646926:web:45c6646dde30c07fa0f31f',
    messagingSenderId: '693469646926',
    projectId: 'ebook-app-76f7d',
    authDomain: 'ebook-app-76f7d.firebaseapp.com',
    storageBucket: 'ebook-app-76f7d.firebasestorage.app',
    measurementId: 'G-N220HBQQDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMtge7wcvAae2qlgFOs6OYE3mH1LJphYg',
    appId: '1:693469646926:android:3928856d922eb2f9a0f31f',
    messagingSenderId: '693469646926',
    projectId: 'ebook-app-76f7d',
    storageBucket: 'ebook-app-76f7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDodpUzZOqPWEjM2cqEIgw4G2-dl1FXF94',
    appId: '1:693469646926:ios:057ff15d466667baa0f31f',
    messagingSenderId: '693469646926',
    projectId: 'ebook-app-76f7d',
    storageBucket: 'ebook-app-76f7d.firebasestorage.app',
    iosBundleId: 'com.example.annoto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDodpUzZOqPWEjM2cqEIgw4G2-dl1FXF94',
    appId: '1:693469646926:ios:057ff15d466667baa0f31f',
    messagingSenderId: '693469646926',
    projectId: 'ebook-app-76f7d',
    storageBucket: 'ebook-app-76f7d.firebasestorage.app',
    iosBundleId: 'com.example.annoto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYeipFKApz2fIZ13yDYy7MmMXyr7N7Tfw',
    appId: '1:693469646926:web:fb1f5d976685388ca0f31f',
    messagingSenderId: '693469646926',
    projectId: 'ebook-app-76f7d',
    authDomain: 'ebook-app-76f7d.firebaseapp.com',
    storageBucket: 'ebook-app-76f7d.firebasestorage.app',
    measurementId: 'G-3W14TKL14F',
  );

}